[[main]]
  identifier = "about"
  pre = ""
  post = ""
  name = "About"
  url = "/about/"
  title = ""
  weight = 1
[[main]]
  identifier = "open-source-package-scanning"
  pre = ""
  post = ""
  name = "Open Source Package Scanning"
  url = "/open-source-package-scanning/"
  title = ""
  weight = 2
[[main]]
  identifier = "posts"
  pre = ""
  post = ""
  name = "Posts"
  url = "/posts/"
  title = ""
  weight = 3
[[main]]
  identifier = "categories"
  pre = ""
  post = ""
  name = "Categories"
  url = "/categories/"
  title = ""
  weight = 4
[[main]]
  identifier = "series"
  pre = ""
  post = ""
  name = "Series"
  url = "/series/"
  title = ""
  weight = 5
